### ISSUE TITLE
Road map for further activities around Mapa 

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#261]
Мапа:
- апісаць як далучыцца да праекта
- апісаць як уносіць змены у праект.
- фіча - падпіскі
- фіча - айфрэйм
- зняць відэа пра Мапатоны і падарожжы.
- Адладзіць пошук па гораду.
- Больш навучання каманды і тымбілдынг.
- фіча - падзеі, запусціць
- запусціць - рэйтынг каштоўнасцяў (навошта)
- палепшыць архітэктуру - больш аўтаномныя сэрвісы.
- злучыць з вікі і будзь валанцёрам.
- тэг-паці зладзіць
- серыя прадаюшчых ворк-шопаў. як знайсці партнёраў за гадзіну.
- запартнерыццца з арганізацыямі для правядзення івэнтаў + з валанцёрскімі арганізацыямі.
- фокус групы з патнцыйнымі карыстальнікамі.
- знайсці сябе. падплесці мапу.
-

**Comment by wellemut** [comment]
Our most important issue this month: 
https://github.com/kartevonmorgen/kartevonmorgen/issues/377

![Tag to new entries](https://user-images.githubusercontent.com/15019030/73229937-dd6e5600-417b-11ea-8d90-5ff0f0eefc9d.png)

Who could solve this?

**Comment by rizomaa** [comment]
> Our most important issue this month:
> [kartevonmorgen/kartevonmorgen#377](https://github.com/kartevonmorgen/kartevonmorgen/issues/377)
> 
> ![Tag to new entries](https://user-images.githubusercontent.com/15019030/73229937-dd6e5600-417b-11ea-8d90-5ff0f0eefc9d.png)
> 
> Who could solve this?

@wellemut please make a separate card for the question. here mostly list of epics.

**Comment by rizomaa** [comment]
Here you can read common thought what we consider for feature development as well as communication plan https://blog.falanster.by/2020/03/03/how-and-why-we-made-belarus-of-tomorrow-more-visible/#What_can_be_a_next_story

**Comment by rizomaa** [comment]
**Тэхнічныя задачы**

- [ ] фіча - падпіскі https://github.com/diglabby/mapa/issues/6 (тут сам рэпазіторый: https://github.com/diglabby/mapa-subscription)
- [ ] фіча - айфрэйм https://github.com/diglabby/mapa/issues/7
- [ ] фіча - падзеі, запусціць 
- [ ] Адладзіць пошук па гораду. (ці ёсць пошук па назве)
- [ ] Палепшыць архітэктуру - больш аўтаномныя сэрвісы (!!!).
- [ ] (магчыма) злучыць з вікі і будзь валанцёрам (API скрыпт).
- [ ] (магчыма) запусціць - рэйтынг каштоўнасцяў (навошта)

**Камунікацыяныя задачы**

- [ ] апісаць як далучыцца да праекта
- [ ] апісаць як уносіць змены у праект.
- [ ] зняць відэа пра Мапатоны і падарожжы.
- [ ] больш навучання каманды і тымбілдынг.
- [ ] тэг-паці зладзіць
- [ ] серыя прадаюшчых ворк-шопаў. як знайсці партнёраў за гадзіну.
- [ ] запартнерыццца з арганізацыямі для правядзення івэнтаў + з валанцёрскімі арганізацыямі.
- [ ] фокус групы з патэнцыйнымі карыстальнікамі.
- [ ] знайсці сябе. падплесці мапу.

ЗЫ
Згрупіраваў спіс на 
1. тэхнічныя, кодзерскія задачы і 
2. камунікацыйныя
